# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from 'c:\\Users\\guill\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

## Creating arrays


In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.7)

array([2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7])

In [9]:
a = [1, 2, 3, 4, 5]
type(a)

list

In [10]:
b = np.array(a)
type(b)

numpy.ndarray

In [11]:
b

array([1, 2, 3, 4, 5])

In [13]:
a[2]

3

In [15]:
a[2] = 10

In [16]:
a

[1, 2, 10, 4, 5]

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [21]:
# Crear una lista de elementos, con incio y fin, indicando la cantidad de divisiones
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Multi-dimensional arrays


In [24]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [26]:
n = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [28]:
n[1,1] = 20

In [29]:
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 7,  8,  9]])

In [32]:
n[2]

array([7, 8, 9])

In [36]:
n[2] = [1, 1, 1]

In [37]:
n

array([[ 1,  2,  3],
       [ 4, 20,  6],
       [ 1,  1,  1]])

In [38]:
n[:,2]

array([3, 6, 1])

## Randomly generated arrays


In [47]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [48]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [49]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

## Element-wise operations


In [51]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [52]:
a + 1

array([1, 2, 3, 4, 5])

array([1.  , 1.44, 1.96, 2.56, 3.24])

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [53]:
a

array([0, 1, 2, 3, 4])

In [56]:
a >= 2

array([False, False,  True,  True,  True])

In [58]:
b = np.array([0, 0, 3, 4, 5])
b

array([0, 0, 3, 4, 5])

In [59]:
a > b

array([False,  True, False, False, False])

In [60]:
a[a>b]

array([1])

## Summarizing operations

In [61]:
a

array([0, 1, 2, 3, 4])

In [62]:
a.min()

0

In [64]:
a.sum()

10

In [68]:
c = np.array([0,1,2])

In [70]:
c.std()

0.816496580927726

In [79]:
a.std()

1.4142135623730951

In [82]:
n.min()

0

In [71]:
c = np.array([[(1,2,3), (4,5,6)], [(7,8,9), (10,11,12)]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
d = np.arange(10,26,5)
d

array([10, 15, 20, 25])

In [75]:
e = np.full((2,2), 7)
e

array([[7, 7],
       [7, 7]])

In [77]:
f = np.eye(5)
f

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [79]:
g = np.empty((3,2))
g

array([[6.23042070e-307, 4.67296746e-307],
       [1.69121096e-306, 1.11261638e-306],
       [1.89146896e-307, 7.56571288e-307]])

In [80]:
np.info(g)

class:  ndarray
shape:  (3, 2)
strides:  (16, 8)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x14b16d94c00
byteorder:  little
byteswap:  False
type: float64


In [84]:
c.shape

(2, 2, 3)

### Next

Linear algebra refresher